#define POSIX_ADVISORY_INFO 
#define                    200809L
#define POSIX_CPUTIME 
#define              200809L
#define POSIX_FSYNC 
#define            200809L
#define POSIX_IPV6 
#define           200809L
#define POSIX_MEMLOCK 
#define              200809L
#define POSIX_MEMLOCK_RANGE 
#define                    200809L
#define POSIX_MESSAGE_PASSING 
#define                      200809L
#define POSIX_MONOTONIC_CLOCK 
#define                      200809L
#define POSIX_RAW_SOCKETS 
#define                  200809L
#define POSIX_SHARED_MEMORY_OBJECTS 
#define                            200809L
#define POSIX_SPAWN 
#define            200809L
#define POSIX_THREAD_ATTR_STACKADDR 
#define                            200809L
#define POSIX_THREAD_ATTR_STACKSIZE 
#define                            200809L
#define POSIX_THREAD_CPUTIME 
#define                     200809L
#define POSIX_THREAD_PRIORITY_SCHEDULING 
#define                                 200809L
#define POSIX_THREAD_PROCESS_SHARED 
#define                            200809L
#define XOPEN_UNIX 
#define           1
